server:
  port: 8081

grpc:
  server:
    port: 9090
    reflection-service-enabled: true

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
